# permissions for end users to view webhooktests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhooktest-viewer-role
rules:
- apiGroups:
  - webhook.operators.coreos.io
  resources:
  - webhooktests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webhook.operators.coreos.io
  resources:
  - webhooktests/status
  verbs:
  - get
