apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: webhook-operator-catalog
  namespace: olm
spec:
  displayName: Webhook Operator Catalog
  image: quay.io/agreene/webhook-operator-index:0.0.2
  sourceType: grpc
